// Units of measure + quantity scaling / formatting helpers.
// Ported from the prototype's data.jsx.

enum UnitKind { count, mass }

class LoUnit {
  final String id;
  final String label;
  final UnitKind kind;
  final String short;
  const LoUnit(this.id, this.label, this.kind, this.short);
}

const List<LoUnit> kUnits = [
  LoUnit('pc', 'pièce', UnitKind.count, ''),
  LoUnit('g', 'g', UnitKind.mass, 'g'),
  LoUnit('kg', 'kg', UnitKind.mass, 'kg'),
  LoUnit('ml', 'ml', UnitKind.mass, 'ml'),
  LoUnit('L', 'L', UnitKind.mass, 'L'),
  LoUnit('cas', 'c. à s', UnitKind.count, 'c.à.s'),
  LoUnit('cac', 'c. à c', UnitKind.count, 'c.à.c'),
  LoUnit('pincee', 'pincée', UnitKind.count, 'pincée'),
];

LoUnit unitById(String id) =>
    kUnits.firstWhere((u) => u.id == id, orElse: () => kUnits.first);

/// Round a scaled quantity sensibly per unit.
double roundQty(double q, String unitId) {
  final u = unitById(unitId);
  if (u.kind == UnitKind.count) {
    if (unitId == 'cas' || unitId == 'cac' || unitId == 'pincee') {
      // allow halves for spoons / pinches
      final v = (q * 2).round() / 2;
      return v < 0.5 ? 0.5 : v;
    }
    final v = q.round();
    return v < 1 ? 1 : v.toDouble();
  }
  // mass / volume
  if (q >= 100) return (q / 10).round() * 10;
  if (q >= 20) return (q / 5).round() * 5;
  return q.round().toDouble();
}

/// French-style pretty number: 1.5 → "1,5", 2 → "2".
String numFr(double n) {
  final r = (n * 100).round() / 100;
  var s = r == r.roundToDouble() ? r.toInt().toString() : r.toString();
  return s.replaceAll('.', ',');
}

class FormattedQty {
  final String value;
  final String suffix;
  const FormattedQty(this.value, this.suffix);
}

/// Format a quantity + unit for display.
FormattedQty fmtQty(double qty, String unitId) {
  final u = unitById(unitId);
  if (u.id == 'pc') return FormattedQty('×${numFr(qty)}', '');
  return FormattedQty(numFr(qty), ' ${u.short}');
}

class ParsedItem {
  final String name;
  final double qty;
  final String unit;
  const ParsedItem({required this.name, required this.qty, required this.unit});
}

ParsedItem parseItemFr(String line) {
  final input = line.trim();
  if (input.isEmpty) {
    return const ParsedItem(name: '', qty: 1, unit: 'pc');
  }

  final regex = RegExp(
    r'^([0-9]+(?:[.,][0-9]+)?)\s*(kg|g|ml|l|L|cas|cac|c\.à\.s|c\.à\.c|cs|cc|pincées?|pincée)?\s*(?:de\s+|d\x27\s+|d’\s+)?(.+)$',
    caseSensitive: false,
  );

  final match = regex.firstMatch(input);
  if (match != null) {
    final qtyStr = match.group(1)!;
    final unitStr = match.group(2)?.toLowerCase();
    final nameStr = match.group(3)!.trim();

    final qty = double.tryParse(qtyStr.replaceAll(',', '.')) ?? 1.0;
    var unit = 'pc';
    if (unitStr != null) {
      if (unitStr == 'g') {
        unit = 'g';
      } else if (unitStr == 'kg') {
        unit = 'kg';
      } else if (unitStr == 'ml') {
        unit = 'ml';
      } else if (unitStr == 'l') {
        unit = 'L';
      } else if (unitStr == 'cas' || unitStr == 'c.à.s' || unitStr == 'cs') {
        unit = 'cas';
      } else if (unitStr == 'cac' || unitStr == 'c.à.c' || unitStr == 'cc') {
        unit = 'cac';
      } else if (unitStr.startsWith('pinc')) {
        unit = 'pincee';
      }
    }
    return ParsedItem(name: nameStr, qty: qty, unit: unit);
  }

  return ParsedItem(name: input, qty: 1.0, unit: 'pc');
}

const Map<String, String> kProductDefaultUnits = {
  'abricot': 'pc',
  'abricots': 'pc',
  'adoucissant': 'pc',
  'agneau': 'g',
  'ail': 'pc',
  'all-purpose cleaner': 'pc',
  'allumettes': 'pc',
  'almond milk': 'L',
  'almonds': 'g',
  'aluminum foil': 'pc',
  'amandes': 'g',
  'amaretto': 'ml',
  'ananas': 'g',
  'apple cider vinegar': 'ml',
  'apple juice': 'L',
  'applesauce': 'pc',
  'apricot': 'pc',
  'apricot jam': 'pc',
  'apricots': 'pc',
  'asperges': 'g',
  'aubergine': 'pc',
  'avocat': 'pc',
  'avocat hass': 'pc',
  'avocats': 'pc',
  'baby wipes': 'pc',
  'bacon': 'g',
  'baguette': 'pc',
  'baking powder': 'sachet',
  'banane': 'pc',
  'bananes': 'pc',
  'band-aids': 'pc',
  'basilic': 'pc',
  'basmati rice': 'g',
  'batteries': 'pc',
  'baume à lèvres': 'pc',
  'beurre': 'g',
  'beurre d\'ail': 'g',
  'beurre de cacahuète': 'cas',
  'beurre demi-sel': 'g',
  'beurre doux': 'g',
  'bicarbonate de soude': 'g',
  'bifteck': 'g',
  'biscottes': 'pc',
  'biscuits': 'pc',
  'biscuits cuillères': 'pc',
  'bière': 'pc',
  'bière artisanale': 'pc',
  'bière blonde': 'pc',
  'bières': 'pc',
  'black tea': 'pc',
  'blackberries': 'g',
  'blanc de poulet': 'g',
  'blueberries': 'g',
  'bonbons': 'g',
  'bouillon de légumes': 'pc',
  'bouillon de volaille': 'pc',
  'brocoli': 'g',
  'brosse à dents': 'pc',
  'burger buns': 'pc',
  'butternut squash': 'pc',
  'cabbage': 'pc',
  'cabillaud': 'g',
  'café': 'g',
  'café décaféiné': 'g',
  'café en grains': 'g',
  'canard': 'g',
  'candies': 'g',
  'cane sugar': 'g',
  'canned corn': 'pc',
  'canned pet food': 'pc',
  'canned sardines': 'pc',
  'canned tuna': 'pc',
  'cannelle': 'cas',
  'capsules de café': 'pc',
  'carotte': 'pc',
  'carottes': 'pc',
  'cashews': 'g',
  'cassonade': 'g',
  'cat litter': 'pc',
  'cauliflower': 'pc',
  'celery': 'pc',
  'cereal': 'g',
  'cerises': 'g',
  'champagne': 'pc',
  'champignons': 'g',
  'cheddar': 'g',
  'cherries': 'g',
  'chia seeds': 'g',
  'chicken breast': 'g',
  'chicken broth': 'pc',
  'chiffon microfibre': 'pc',
  'chips': 'pc',
  'chocolat': 'g',
  'chocolat au lait': 'g',
  'chocolat noir': 'g',
  'chocolate chips': 'g',
  'chocolate croissant': 'pc',
  'chocolate spread': 'pc',
  'chou rouge': 'pc',
  'chou vert': 'pc',
  'chou-fleur': 'pc',
  'cider': 'L',
  'cidre': 'L',
  'cinnamon': 'cas',
  'citron': 'pc',
  'citron jaune': 'pc',
  'citron vert': 'pc',
  'citrons': 'pc',
  'coarse salt': 'g',
  'coca': 'pc',
  'coca-cola': 'pc',
  'coconut oil': 'g',
  'cod': 'g',
  'coffee beans': 'g',
  'coffee pods': 'pc',
  'cola': 'pc',
  'colin': 'g',
  'compote': 'pc',
  'compote de pommes': 'pc',
  'concombre': 'pc',
  'confiture': 'pc',
  'confiture d\'abricots': 'pc',
  'confiture de fraises': 'pc',
  'cooked ham': 'pc',
  'cookies': 'pc',
  'coton-tiges': 'pc',
  'cotons': 'pc',
  'cotton pads': 'pc',
  'cotton swabs': 'pc',
  'couches': 'pc',
  'courge butternut': 'pc',
  'courgette': 'pc',
  'courgettes': 'pc',
  'craft beer': 'pc',
  'cream cheese': 'g',
  'crevettes': 'g',
  'crevettes décortiquées': 'g',
  'croissants': 'pc',
  'croquettes': 'pc',
  'crème': 'ml',
  'crème fraîche': 'ml',
  'crème hydratante': 'pc',
  'crème liquide': 'ml',
  'cucumber': 'pc',
  'cumin': 'cas',
  'curry en poudre': 'cas',
  'curry powder': 'cas',
  'céleri': 'pc',
  'céréales': 'g',
  'côtes de porc': 'g',
  'dark chocolate': 'g',
  'decaf coffee': 'g',
  'dentifrice': 'pc',
  'deodorant': 'pc',
  'diapers': 'pc',
  'dijon mustard': 'pc',
  'dinde': 'g',
  'dishwasher tablets': 'pc',
  'dishwashing liquid': 'pc',
  'doliprane': 'pc',
  'double de tomate': 'cas',
  'dry yeast': 'sachet',
  'déodorant': 'pc',
  'détartrant': 'pc',
  'eau': 'L',
  'eau gazeuse': 'L',
  'emmental': 'g',
  'escalope de dinde': 'g',
  'escalope de porc': 'g',
  'essuie-tout': 'pc',
  'extrait de vanille': 'ml',
  'fabric softener': 'pc',
  'farine': 'g',
  'feta': 'g',
  'filet de cabillaud': 'g',
  'filet de poulet': 'g',
  'film étirable': 'pc',
  'fleur de sel': 'g',
  'flocons d\'avoine': 'g',
  'flour tortillas': 'pc',
  'fraise': 'g',
  'fraises': 'g',
  'framboises': 'g',
  'freezer bags': 'pc',
  'french fries': 'g',
  'fresh spinach': 'g',
  'frites': 'g',
  'fromage': 'g',
  'fromage blanc': 'g',
  'fromage de chèvre': 'pc',
  'fromage râpé': 'g',
  'fromage à tartiner': 'g',
  'frozen fish': 'g',
  'frozen pizza': 'pc',
  'frozen vegetables': 'g',
  'garam masala': 'cas',
  'gel douche': 'pc',
  'gel hydroalcoolique': 'pc',
  'gingembre': 'g',
  'glace': 'pc',
  'glass cleaner': 'pc',
  'gluten-free bread': 'pc',
  'goat cheese': 'pc',
  'graines de chia': 'g',
  'graines de sésame': 'g',
  'grapefruit': 'pc',
  'grated parmesan': 'g',
  'greek yogurt': 'pc',
  'green beans': 'g',
  'green pesto': 'pc',
  'green tea': 'pc',
  'gros sel': 'g',
  'ground beef': 'g',
  'gruyère râpé': 'g',
  'hake': 'g',
  'hand sanitizer': 'pc',
  'hand soap': 'pc',
  'haricots rouges': 'g',
  'haricots verts': 'g',
  'hass avocado': 'pc',
  'hazelnuts': 'g',
  'herbes de provence': 'cas',
  'houmous': 'pc',
  'huile': 'L',
  'huile d\'olive': 'L',
  'huile de coco': 'g',
  'huile de tournesol': 'L',
  'ice cream': 'pc',
  'ice tea': 'pc',
  'iceberg lettuce': 'pc',
  'jam': 'pc',
  'jambon': 'pc',
  'jambon cru': 'pc',
  'jambon cuit': 'pc',
  'jasmine rice': 'g',
  'jus d\'orange': 'L',
  'jus de pomme': 'L',
  'ketchup': 'pc',
  'kidney beans': 'g',
  'kiwi': 'pc',
  'kiwis': 'pc',
  'lager': 'pc',
  'lait': 'L',
  'lait d\'amande': 'L',
  'lait d\'avoine': 'L',
  'lait de soja': 'L',
  'lamb': 'g',
  'laundry detergent': 'pc',
  'laundry pods': 'pc',
  'leek': 'pc',
  'leeks': 'pc',
  'lemon': 'pc',
  'lemonade': 'L',
  'lentilles corail': 'g',
  'lentilles vertes': 'g',
  'lessive': 'pc',
  'lessive liquide': 'pc',
  'levure boulangère': 'sachet',
  'levure chimique': 'sachet',
  'lime': 'pc',
  'limescale remover': 'pc',
  'limonade': 'L',
  'lingettes bébé': 'pc',
  'lip balm': 'pc',
  'liquid detergent': 'pc',
  'liquide vaisselle': 'pc',
  'litière': 'pc',
  'légumes surgelés': 'g',
  'magret de canard': 'g',
  'mango': 'pc',
  'mangue': 'pc',
  'maple syrup': 'ml',
  'margarine': 'g',
  'mascarpone': 'g',
  'matches': 'pc',
  'mayonnaise': 'pc',
  'maïs en boîte': 'pc',
  'melon': 'pc',
  'microfiber cloth': 'pc',
  'miel': 'cas',
  'milk chocolate': 'g',
  'moisturizer': 'pc',
  'mouchoirs': 'pc',
  'mousse à raser': 'pc',
  'moutarde de dijon': 'pc',
  'mozzarella di bufala': 'pc',
  'muesli': 'g',
  'muffins': 'pc',
  'myrtilles': 'g',
  'mûres': 'g',
  'nettoyant multi-surfaces': 'pc',
  'nettoyant multi-usages': 'pc',
  'noisettes': 'g',
  'noix de cajou': 'g',
  'noix de muscade': 'pc',
  'nutmeg': 'pc',
  'oat milk': 'L',
  'oatmeal': 'g',
  'oeuf': 'pc',
  'oeufs': 'pc',
  'oignon': 'pc',
  'oignon rouge': 'pc',
  'oignons': 'pc',
  'olives': 'g',
  'orange': 'pc',
  'orange juice': 'L',
  'oranges': 'pc',
  'oregano': 'cas',
  'origan': 'cas',
  'pads': 'pc',
  'pain': 'pc',
  'pain au chocolat': 'pc',
  'pain de campagne': 'pc',
  'pain de mie': 'pc',
  'pain sans gluten': 'pc',
  'painkillers': 'pc',
  'pains burger': 'pc',
  'pamplemousse': 'pc',
  'pancake': 'pc',
  'pancakes': 'pc',
  'pansements': 'pc',
  'paper towel': 'pc',
  'papier aluminium': 'pc',
  'papier cuisson': 'pc',
  'papier toilette': 'pc',
  'paprika doux': 'cas',
  'paracétamol': 'pc',
  'parchment paper': 'pc',
  'parmesan râpé': 'g',
  'pastilles lave-linge': 'pc',
  'pastilles lave-vaisselle': 'pc',
  'pastèque': 'pc',
  'patates': 'kg',
  'patates douces': 'g',
  'pavé de saumon': 'g',
  'peach': 'pc',
  'pear': 'pc',
  'peas': 'g',
  'peeled shrimp': 'g',
  'persil': 'pc',
  'pesto alla genovese': 'pc',
  'pesto rosso': 'pc',
  'pet food': 'pc',
  'petits pois': 'g',
  'pignons de pin': 'g',
  'piles': 'pc',
  'pizza surgelée': 'pc',
  'plastic wrap': 'pc',
  'poire': 'pc',
  'poireau': 'pc',
  'poireaux': 'pc',
  'poisson': 'g',
  'poisson surgelé': 'g',
  'poivre': 'pincee',
  'poivron': 'pc',
  'polenta': 'g',
  'pomme': 'pc',
  'pomme de terre': 'kg',
  'pommes': 'pc',
  'pommes de terre': 'kg',
  'pommes gala': 'pc',
  'porc': 'g',
  'pork chop': 'g',
  'portobellos': 'pc',
  'potimarron': 'pc',
  'poulet': 'g',
  'produit vitres': 'pc',
  'prosciutto': 'pc',
  'pumpkin': 'pc',
  'pâte brisée': 'pc',
  'pâte à gaufres': 'g',
  'pâte à tartiner': 'pc',
  'pâtes': 'g',
  'pâtes penne': 'g',
  'pâtée pour chat': 'pc',
  'pâtée pour chien': 'pc',
  'pépites de chocolat': 'g',
  'pêche': 'pc',
  'quinoa': 'g',
  'quinoa rouge': 'g',
  'radis': 'pc',
  'radishes': 'pc',
  'rasoir': 'pc',
  'rasoirs': 'pc',
  'razor': 'pc',
  'razors': 'pc',
  'red cabbage': 'pc',
  'red lentils': 'g',
  'red pesto': 'pc',
  'red quinoa': 'g',
  'red wine': 'pc',
  'ricotta': 'g',
  'riz': 'g',
  'riz basmati': 'g',
  'riz jasmin': 'g',
  'riz rond': 'g',
  'rolled oats': 'g',
  'roquefort': 'g',
  'rustic bread': 'pc',
  'sacs congélation': 'pc',
  'sacs poubelle': 'pc',
  'salade': 'pc',
  'salade iceberg': 'pc',
  'salted butter': 'g',
  'sandwich bread': 'pc',
  'sardines': 'pc',
  'sardines à l\'huile': 'pc',
  'sauce aigre-douce': 'ml',
  'sauce barbecue': 'ml',
  'sauce pesto': 'pc',
  'sauce soja': 'ml',
  'sauce sriracha': 'pc',
  'sauce tomate': 'ml',
  'sauce tomate basilic': 'pc',
  'saucisses': 'pc',
  'saumon': 'g',
  'saumon fumé': 'g',
  'savon': 'pc',
  'savon pour les mains': 'pc',
  'sel': 'pincee',
  'semoule': 'g',
  'serviettes hygiéniques': 'pc',
  'sesame seeds': 'g',
  'shampoing': 'pc',
  'shampoo': 'pc',
  'shampooing': 'pc',
  'shaving cream': 'pc',
  'shower gel': 'pc',
  'shredded gruyere': 'g',
  'sirop d\'érable': 'ml',
  'smoked salmon': 'g',
  'soap': 'pc',
  'sopalin': 'pc',
  'sorbet': 'pc',
  'soy milk': 'L',
  'spaghetti': 'g',
  'sparkling water': 'L',
  'sponge': 'pc',
  'sriracha': 'pc',
  'steak': 'g',
  'steak de bœuf': 'g',
  'strawberry jam': 'pc',
  'sucre': 'g',
  'sucre de canne': 'g',
  'sucre glace': 'g',
  'sunflower oil': 'L',
  'sushi rice': 'g',
  'sweet paprika': 'cas',
  'tampons': 'pc',
  'tempeh': 'g',
  'thon en boîte': 'pc',
  'thé glacé': 'pc',
  'thé noir': 'pc',
  'thé vert': 'pc',
  'tissues': 'pc',
  'tofu ferme': 'g',
  'toilet paper': 'pc',
  'tomate': 'pc',
  'tomates': 'pc',
  'tomato basil sauce': 'pc',
  'tomato sauce': 'ml',
  'toothbrush': 'pc',
  'toothpaste': 'pc',
  'tortillas de blé': 'pc',
  'trash bags': 'pc',
  'turkey': 'g',
  'unsalted butter': 'g',
  'vanilla extract': 'ml',
  'vegetable broth': 'pc',
  'viande': 'g',
  'viande hachée': 'g',
  'viande hachée de boeuf': 'g',
  'vin': 'pc',
  'vin blanc': 'pc',
  'vin rouge': 'pc',
  'vinaigre balsamique': 'ml',
  'vinaigre blanc': 'L',
  'vinaigre de cidre': 'ml',
  'vinaigrette': 'cas',
  'watermelon': 'pc',
  'white cleaning vinegar': 'L',
  'white wine': 'pc',
  'yaourt': 'pc',
  'yaourt grec': 'pc',
  'yaourts': 'pc',
  'épinards frais': 'g',
  'éponge': 'pc',
  'éponges': 'pc',
  'œuf': 'pc',
  'œufs': 'pc',
};

const Map<String, String> kProductCategories = {
  'abricot': 'Fruits & Légumes',
  'abricots': 'Fruits & Légumes',
  'adoucissant': 'Hygiène & Entretien',
  'agneau': 'Boucherie & Poissonnerie',
  'ail': 'Fruits & Légumes',
  'all-purpose cleaner': 'Hygiène & Entretien',
  'allumettes': 'Hygiène & Entretien',
  'almond milk': 'Produits Laitiers & Œufs',
  'almonds': 'Épicerie',
  'aluminum foil': 'Hygiène & Entretien',
  'amandes': 'Épicerie',
  'amaretto': 'Épicerie',
  'ananas': 'Épicerie',
  'apple cider vinegar': 'Épicerie',
  'apple juice': 'Boissons',
  'applesauce': 'Épicerie',
  'apricot': 'Fruits & Légumes',
  'apricot jam': 'Épicerie',
  'apricots': 'Fruits & Légumes',
  'asperges': 'Fruits & Légumes',
  'aubergine': 'Fruits & Légumes',
  'aubergines': 'Fruits & Légumes',
  'avocat': 'Fruits & Légumes',
  'avocat hass': 'Fruits & Légumes',
  'avocats': 'Fruits & Légumes',
  'baby wipes': 'Hygiène & Entretien',
  'bacon': 'Boucherie & Poissonnerie',
  'baguette': 'Boulangerie',
  'baking powder': 'Épicerie',
  'banane': 'Fruits & Légumes',
  'bananes': 'Fruits & Légumes',
  'band-aids': 'Hygiène & Entretien',
  'basilic': 'Fruits & Légumes',
  'basmati rice': 'Épicerie',
  'batteries': 'Hygiène & Entretien',
  'baume à lèvres': 'Hygiène & Entretien',
  'beurre': 'Produits Laitiers & Œufs',
  'beurre d\'ail': 'Produits Laitiers & Œufs',
  'beurre de cacahuète': 'Épicerie',
  'beurre demi-sel': 'Produits Laitiers & Œufs',
  'beurre doux': 'Produits Laitiers & Œufs',
  'bicarbonate de soude': 'Hygiène & Entretien',
  'bifteck': 'Boucherie & Poissonnerie',
  'biscottes': 'Boulangerie',
  'biscuits': 'Épicerie',
  'biscuits cuillères': 'Boulangerie',
  'bière': 'Boissons',
  'bière artisanale': 'Boissons',
  'bière blonde': 'Boissons',
  'bières': 'Boissons',
  'black tea': 'Boissons',
  'blackberries': 'Fruits & Légumes',
  'blanc de poulet': 'Boucherie & Poissonnerie',
  'blueberries': 'Fruits & Légumes',
  'bonbons': 'Épicerie',
  'bouillon de légumes': 'Épicerie',
  'bouillon de volaille': 'Épicerie',
  'brocoli': 'Fruits & Légumes',
  'brosse à dents': 'Hygiène & Entretien',
  'burger buns': 'Boulangerie',
  'butternut squash': 'Fruits & Légumes',
  'cabbage': 'Fruits & Légumes',
  'cabillaud': 'Boucherie & Poissonnerie',
  'café': 'Épicerie',
  'café décaféiné': 'Boissons',
  'café en grains': 'Boissons',
  'café moulu': 'Épicerie',
  'canard': 'Boucherie & Poissonnerie',
  'candies': 'Épicerie',
  'cane sugar': 'Épicerie',
  'canned corn': 'Épicerie',
  'canned pet food': 'Hygiène & Entretien',
  'canned sardines': 'Épicerie',
  'canned tuna': 'Épicerie',
  'cannelle': 'Épicerie',
  'capsules de café': 'Boissons',
  'carotte': 'Fruits & Légumes',
  'carottes': 'Fruits & Légumes',
  'cashews': 'Épicerie',
  'cassonade': 'Épicerie',
  'cat litter': 'Hygiène & Entretien',
  'cauliflower': 'Fruits & Légumes',
  'celery': 'Fruits & Légumes',
  'cereal': 'Épicerie',
  'cerises': 'Fruits & Légumes',
  'champagne': 'Boissons',
  'champignons': 'Fruits & Légumes',
  'cheddar': 'Produits Laitiers & Œufs',
  'cherries': 'Fruits & Légumes',
  'chia seeds': 'Épicerie',
  'chicken breast': 'Boucherie & Poissonnerie',
  'chicken broth': 'Épicerie',
  'chiffon microfibre': 'Hygiène & Entretien',
  'chips': 'Épicerie',
  'chocolat': 'Épicerie',
  'chocolat au lait': 'Épicerie',
  'chocolat noir': 'Épicerie',
  'chocolate chips': 'Épicerie',
  'chocolate croissant': 'Boulangerie',
  'chocolate spread': 'Épicerie',
  'chou rouge': 'Fruits & Légumes',
  'chou vert': 'Fruits & Légumes',
  'chou-fleur': 'Fruits & Légumes',
  'cider': 'Boissons',
  'cidre': 'Boissons',
  'cinnamon': 'Épicerie',
  'citron': 'Fruits & Légumes',
  'citron jaune': 'Fruits & Légumes',
  'citron vert': 'Fruits & Légumes',
  'citrons': 'Fruits & Légumes',
  'coarse salt': 'Épicerie',
  'coca': 'Boissons',
  'coca-cola': 'Boissons',
  'coconut oil': 'Épicerie',
  'cod': 'Boucherie & Poissonnerie',
  'coffee beans': 'Boissons',
  'coffee pods': 'Boissons',
  'cola': 'Boissons',
  'colin': 'Boucherie & Poissonnerie',
  'compote': 'Épicerie',
  'compote de pommes': 'Épicerie',
  'concombre': 'Fruits & Légumes',
  'confiture': 'Épicerie',
  'confiture d\'abricots': 'Épicerie',
  'confiture de fraises': 'Épicerie',
  'cooked ham': 'Boucherie & Poissonnerie',
  'cookies': 'Épicerie',
  'coton-tiges': 'Hygiène & Entretien',
  'cotons': 'Hygiène & Entretien',
  'cotton pads': 'Hygiène & Entretien',
  'cotton swabs': 'Hygiène & Entretien',
  'couches': 'Hygiène & Entretien',
  'courge butternut': 'Fruits & Légumes',
  'courgette': 'Fruits & Légumes',
  'courgettes': 'Fruits & Légumes',
  'craft beer': 'Boissons',
  'cream cheese': 'Produits Laitiers & Œufs',
  'crevettes': 'Boucherie & Poissonnerie',
  'crevettes décortiquées': 'Boucherie & Poissonnerie',
  'croissant': 'Boulangerie',
  'croissants': 'Boulangerie',
  'croquettes': 'Hygiène & Entretien',
  'croûtons': 'Boulangerie',
  'crème': 'Produits Laitiers & Œufs',
  'crème fraîche': 'Produits Laitiers & Œufs',
  'crème hydratante': 'Hygiène & Entretien',
  'crème liquide': 'Produits Laitiers & Œufs',
  'cucumber': 'Fruits & Légumes',
  'cumin': 'Épicerie',
  'curry en poudre': 'Épicerie',
  'curry powder': 'Épicerie',
  'céleri': 'Fruits & Légumes',
  'céréales': 'Épicerie',
  'côtes de porc': 'Boucherie & Poissonnerie',
  'dark chocolate': 'Épicerie',
  'decaf coffee': 'Boissons',
  'dentifrice': 'Hygiène & Entretien',
  'deodorant': 'Hygiène & Entretien',
  'diapers': 'Hygiène & Entretien',
  'dijon mustard': 'Épicerie',
  'dinde': 'Boucherie & Poissonnerie',
  'dishwasher tablets': 'Hygiène & Entretien',
  'dishwashing liquid': 'Hygiène & Entretien',
  'doliprane': 'Hygiène & Entretien',
  'double de tomate': 'Épicerie',
  'dry yeast': 'Épicerie',
  'déodorant': 'Hygiène & Entretien',
  'détartrant': 'Hygiène & Entretien',
  'eau': 'Boissons',
  'eau gazeuse': 'Boissons',
  'emmental': 'Produits Laitiers & Œufs',
  'escalope de dinde': 'Boucherie & Poissonnerie',
  'escalope de porc': 'Boucherie & Poissonnerie',
  'essuie-tout': 'Hygiène & Entretien',
  'extrait de vanille': 'Épicerie',
  'fabric softener': 'Hygiène & Entretien',
  'farine': 'Épicerie',
  'feta': 'Produits Laitiers & Œufs',
  'filet de cabillaud': 'Boucherie & Poissonnerie',
  'filet de poulet': 'Boucherie & Poissonnerie',
  'film étirable': 'Hygiène & Entretien',
  'fleur de sel': 'Épicerie',
  'flocons d\'avoine': 'Épicerie',
  'flour tortillas': 'Boulangerie',
  'fraise': 'Fruits & Légumes',
  'fraises': 'Fruits & Légumes',
  'framboises': 'Fruits & Légumes',
  'freezer bags': 'Hygiène & Entretien',
  'french fries': 'Épicerie',
  'fresh spinach': 'Fruits & Légumes',
  'frites': 'Épicerie',
  'fromage': 'Produits Laitiers & Œufs',
  'fromage blanc': 'Produits Laitiers & Œufs',
  'fromage de chèvre': 'Produits Laitiers & Œufs',
  'fromage râpé': 'Produits Laitiers & Œufs',
  'fromage à tartiner': 'Produits Laitiers & Œufs',
  'frozen fish': 'Épicerie',
  'frozen pizza': 'Épicerie',
  'frozen vegetables': 'Épicerie',
  'garam masala': 'Épicerie',
  'gel douche': 'Hygiène & Entretien',
  'gel hydroalcoolique': 'Hygiène & Entretien',
  'gingembre': 'Fruits & Légumes',
  'glace': 'Épicerie',
  'glass cleaner': 'Hygiène & Entretien',
  'gluten-free bread': 'Boulangerie',
  'goat cheese': 'Produits Laitiers & Œufs',
  'graines de chia': 'Épicerie',
  'graines de sésame': 'Épicerie',
  'grapefruit': 'Fruits & Légumes',
  'grated parmesan': 'Produits Laitiers & Œufs',
  'greek yogurt': 'Produits Laitiers & Œufs',
  'green beans': 'Fruits & Légumes',
  'green pesto': 'Épicerie',
  'green tea': 'Boissons',
  'gros sel': 'Épicerie',
  'ground beef': 'Boucherie & Poissonnerie',
  'gruyère râpé': 'Produits Laitiers & Œufs',
  'hake': 'Boucherie & Poissonnerie',
  'hand sanitizer': 'Hygiène & Entretien',
  'hand soap': 'Hygiène & Entretien',
  'haricots rouges': 'Épicerie',
  'haricots verts': 'Fruits & Légumes',
  'hass avocado': 'Fruits & Légumes',
  'hazelnuts': 'Épicerie',
  'herbes de provence': 'Épicerie',
  'houmous': 'Épicerie',
  'huile': 'Épicerie',
  'huile d\'olive': 'Épicerie',
  'huile de coco': 'Épicerie',
  'huile de tournesol': 'Épicerie',
  'ice cream': 'Épicerie',
  'ice tea': 'Boissons',
  'iceberg lettuce': 'Fruits & Légumes',
  'jam': 'Épicerie',
  'jambon': 'Boucherie & Poissonnerie',
  'jambon cru': 'Boucherie & Poissonnerie',
  'jambon cuit': 'Boucherie & Poissonnerie',
  'jasmine rice': 'Épicerie',
  'jus': 'Boissons',
  'jus d\'orange': 'Boissons',
  'jus de pomme': 'Boissons',
  'ketchup': 'Épicerie',
  'kidney beans': 'Épicerie',
  'kiwi': 'Fruits & Légumes',
  'kiwis': 'Fruits & Légumes',
  'lager': 'Boissons',
  'lait': 'Produits Laitiers & Œufs',
  'lait d\'amande': 'Produits Laitiers & Œufs',
  'lait d\'avoine': 'Produits Laitiers & Œufs',
  'lait de coco': 'Épicerie',
  'lait de soja': 'Produits Laitiers & Œufs',
  'lamb': 'Boucherie & Poissonnerie',
  'laundry detergent': 'Hygiène & Entretien',
  'laundry pods': 'Hygiène & Entretien',
  'leek': 'Fruits & Légumes',
  'leeks': 'Fruits & Légumes',
  'lemon': 'Fruits & Légumes',
  'lemonade': 'Boissons',
  'lentilles corail': 'Épicerie',
  'lentilles vertes': 'Épicerie',
  'lessive': 'Hygiène & Entretien',
  'lessive liquide': 'Hygiène & Entretien',
  'levure': 'Épicerie',
  'levure boulangère': 'Épicerie',
  'levure chimique': 'Épicerie',
  'lime': 'Fruits & Légumes',
  'limescale remover': 'Hygiène & Entretien',
  'limonade': 'Boissons',
  'lingettes bébé': 'Hygiène & Entretien',
  'lip balm': 'Hygiène & Entretien',
  'liquid detergent': 'Hygiène & Entretien',
  'liquide vaisselle': 'Hygiène & Entretien',
  'litière': 'Hygiène & Entretien',
  'légumes surgelés': 'Épicerie',
  'magret de canard': 'Boucherie & Poissonnerie',
  'mango': 'Fruits & Légumes',
  'mangue': 'Fruits & Légumes',
  'maple syrup': 'Épicerie',
  'margarine': 'Produits Laitiers & Œufs',
  'mascarpone': 'Produits Laitiers & Œufs',
  'matches': 'Hygiène & Entretien',
  'mayonnaise': 'Épicerie',
  'maïs en boîte': 'Épicerie',
  'melon': 'Fruits & Légumes',
  'microfiber cloth': 'Hygiène & Entretien',
  'miel': 'Épicerie',
  'milk chocolate': 'Épicerie',
  'moisturizer': 'Hygiène & Entretien',
  'mouchoirs': 'Hygiène & Entretien',
  'mousse à raser': 'Hygiène & Entretien',
  'moutarde de dijon': 'Épicerie',
  'mozzarella di bufala': 'Produits Laitiers & Œufs',
  'muesli': 'Épicerie',
  'muffins': 'Boulangerie',
  'myrtilles': 'Fruits & Légumes',
  'mûres': 'Fruits & Légumes',
  'nettoyant multi-surfaces': 'Hygiène & Entretien',
  'nettoyant multi-usages': 'Hygiène & Entretien',
  'noisettes': 'Épicerie',
  'noix de cajou': 'Épicerie',
  'noix de muscade': 'Épicerie',
  'nutmeg': 'Épicerie',
  'oat milk': 'Produits Laitiers & Œufs',
  'oatmeal': 'Épicerie',
  'oeuf': 'Produits Laitiers & Œufs',
  'oeufs': 'Produits Laitiers & Œufs',
  'oignon': 'Fruits & Légumes',
  'oignon rouge': 'Fruits & Légumes',
  'oignons': 'Fruits & Légumes',
  'olives': 'Fruits & Légumes',
  'orange': 'Fruits & Légumes',
  'orange juice': 'Boissons',
  'oranges': 'Fruits & Légumes',
  'oregano': 'Épicerie',
  'origan': 'Épicerie',
  'pads': 'Hygiène & Entretien',
  'pain': 'Boulangerie',
  'pain au chocolat': 'Boulangerie',
  'pain complet': 'Boulangerie',
  'pain de campagne': 'Boulangerie',
  'pain de mie': 'Boulangerie',
  'pain sans gluten': 'Boulangerie',
  'painkillers': 'Hygiène & Entretien',
  'pains burger': 'Boulangerie',
  'pamplemousse': 'Fruits & Légumes',
  'pancake': 'Boulangerie',
  'pancakes': 'Boulangerie',
  'pansements': 'Hygiène & Entretien',
  'paper towel': 'Hygiène & Entretien',
  'papier aluminium': 'Hygiène & Entretien',
  'papier cuisson': 'Hygiène & Entretien',
  'papier toilette': 'Hygiène & Entretien',
  'paprika doux': 'Épicerie',
  'paracétamol': 'Hygiène & Entretien',
  'parchment paper': 'Hygiène & Entretien',
  'parmesan': 'Produits Laitiers & Œufs',
  'parmesan râpé': 'Produits Laitiers & Œufs',
  'pastilles lave-linge': 'Hygiène & Entretien',
  'pastilles lave-vaisselle': 'Hygiène & Entretien',
  'pastèque': 'Fruits & Légumes',
  'patates': 'Fruits & Légumes',
  'patates douces': 'Épicerie',
  'pavé de saumon': 'Boucherie & Poissonnerie',
  'peach': 'Fruits & Légumes',
  'pear': 'Fruits & Légumes',
  'peas': 'Fruits & Légumes',
  'peeled shrimp': 'Boucherie & Poissonnerie',
  'persil': 'Fruits & Légumes',
  'pesto alla genovese': 'Épicerie',
  'pesto rosso': 'Épicerie',
  'pet food': 'Hygiène & Entretien',
  'petits pois': 'Fruits & Légumes',
  'pignons de pin': 'Épicerie',
  'piles': 'Hygiène & Entretien',
  'pizza surgelée': 'Épicerie',
  'plastic wrap': 'Hygiène & Entretien',
  'poire': 'Fruits & Légumes',
  'poireau': 'Fruits & Légumes',
  'poireaux': 'Fruits & Légumes',
  'pois chiches': 'Épicerie',
  'poisson': 'Boucherie & Poissonnerie',
  'poisson surgelé': 'Épicerie',
  'poivre': 'Épicerie',
  'poivron': 'Fruits & Légumes',
  'polenta': 'Épicerie',
  'pomme': 'Fruits & Légumes',
  'pomme de terre': 'Fruits & Légumes',
  'pommes': 'Fruits & Légumes',
  'pommes de terre': 'Fruits & Légumes',
  'pommes gala': 'Fruits & Légumes',
  'porc': 'Boucherie & Poissonnerie',
  'pork chop': 'Boucherie & Poissonnerie',
  'portobello': 'Fruits & Légumes',
  'portobellos': 'Fruits & Légumes',
  'potimarron': 'Fruits & Légumes',
  'poulet': 'Boucherie & Poissonnerie',
  'produit vitres': 'Hygiène & Entretien',
  'prosciutto': 'Boucherie & Poissonnerie',
  'pumpkin': 'Fruits & Légumes',
  'pâte brisée': 'Boulangerie',
  'pâte de curry': 'Épicerie',
  'pâte à tartiner': 'Épicerie',
  'pâtes': 'Épicerie',
  'pâtes penne': 'Épicerie',
  'pâtée pour chat': 'Hygiène & Entretien',
  'pâtée pour chien': 'Hygiène & Entretien',
  'pépites de chocolat': 'Épicerie',
  'pêche': 'Fruits & Légumes',
  'quinoa': 'Épicerie',
  'quinoa rouge': 'Épicerie',
  'radis': 'Fruits & Légumes',
  'radishes': 'Fruits & Légumes',
  'rasoir': 'Hygiène & Entretien',
  'rasoirs': 'Hygiène & Entretien',
  'razor': 'Hygiène & Entretien',
  'razors': 'Hygiène & Entretien',
  'red cabbage': 'Fruits & Légumes',
  'red lentils': 'Épicerie',
  'red pesto': 'Épicerie',
  'red quinoa': 'Épicerie',
  'red wine': 'Boissons',
  'ricotta': 'Produits Laitiers & Œufs',
  'riz': 'Épicerie',
  'riz basmati': 'Épicerie',
  'riz jasmin': 'Épicerie',
  'riz rond': 'Épicerie',
  'rolled oats': 'Épicerie',
  'roquefort': 'Produits Laitiers & Œufs',
  'rustic bread': 'Boulangerie',
  'sacs congélation': 'Hygiène & Entretien',
  'sacs poubelle': 'Hygiène & Entretien',
  'salade': 'Fruits & Légumes',
  'salade iceberg': 'Fruits & Légumes',
  'salted butter': 'Produits Laitiers & Œufs',
  'sandwich bread': 'Boulangerie',
  'sardines': 'Boucherie & Poissonnerie',
  'sardines à l\'huile': 'Épicerie',
  'sauce aigre-douce': 'Épicerie',
  'sauce barbecue': 'Épicerie',
  'sauce pesto': 'Épicerie',
  'sauce soja': 'Épicerie',
  'sauce sriracha': 'Épicerie',
  'sauce tomate': 'Épicerie',
  'sauce tomate basilic': 'Épicerie',
  'saucisses': 'Boucherie & Poissonnerie',
  'saumon': 'Boucherie & Poissonnerie',
  'saumon fumé': 'Boucherie & Poissonnerie',
  'savon': 'Hygiène & Entretien',
  'savon pour les mains': 'Hygiène & Entretien',
  'sel': 'Épicerie',
  'semoule': 'Épicerie',
  'serviettes hygiéniques': 'Hygiène & Entretien',
  'sesame seeds': 'Épicerie',
  'shampoing': 'Hygiène & Entretien',
  'shampoo': 'Hygiène & Entretien',
  'shampooing': 'Hygiène & Entretien',
  'shaving cream': 'Hygiène & Entretien',
  'shower gel': 'Hygiène & Entretien',
  'shredded gruyere': 'Produits Laitiers & Œufs',
  'sirop d\'érable': 'Épicerie',
  'smoked salmon': 'Boucherie & Poissonnerie',
  'soap': 'Hygiène & Entretien',
  'soda': 'Boissons',
  'sopalin': 'Hygiène & Entretien',
  'sorbet': 'Épicerie',
  'soy milk': 'Produits Laitiers & Œufs',
  'spaghetti': 'Épicerie',
  'sparkling water': 'Boissons',
  'sponge': 'Hygiène & Entretien',
  'sriracha': 'Épicerie',
  'steak': 'Boucherie & Poissonnerie',
  'steak de bœuf': 'Boucherie & Poissonnerie',
  'strawberry jam': 'Épicerie',
  'sucre': 'Épicerie',
  'sucre de canne': 'Épicerie',
  'sucre glace': 'Épicerie',
  'sunflower oil': 'Épicerie',
  'sushi rice': 'Épicerie',
  'sweet paprika': 'Épicerie',
  'tampons': 'Hygiène & Entretien',
  'tempeh': 'Épicerie',
  'thon en boîte': 'Épicerie',
  'thé glacé': 'Boissons',
  'thé noir': 'Boissons',
  'thé vert': 'Boissons',
  'tissues': 'Hygiène & Entretien',
  'tofu ferme': 'Épicerie',
  'toilet paper': 'Hygiène & Entretien',
  'tomate': 'Fruits & Légumes',
  'tomates': 'Fruits & Légumes',
  'tomates concassées': 'Épicerie',
  'tomato basil sauce': 'Épicerie',
  'tomato sauce': 'Épicerie',
  'toothbrush': 'Hygiène & Entretien',
  'toothpaste': 'Hygiène & Entretien',
  'tortillas de blé': 'Boulangerie',
  'trash bags': 'Hygiène & Entretien',
  'turkey': 'Boucherie & Poissonnerie',
  'unsalted butter': 'Produits Laitiers & Œufs',
  'vanilla extract': 'Épicerie',
  'vegetable broth': 'Épicerie',
  'viande': 'Boucherie & Poissonnerie',
  'viande hachée': 'Boucherie & Poissonnerie',
  'viande hachée de boeuf': 'Boucherie & Poissonnerie',
  'vin': 'Boissons',
  'vin blanc': 'Boissons',
  'vin rouge': 'Boissons',
  'vinaigre balsamique': 'Épicerie',
  'vinaigre blanc': 'Hygiène & Entretien',
  'vinaigre de cidre': 'Épicerie',
  'vinaigrette': 'Épicerie',
  'watermelon': 'Fruits & Légumes',
  'white cleaning vinegar': 'Hygiène & Entretien',
  'white wine': 'Boissons',
  'yaourt': 'Produits Laitiers & Œufs',
  'yaourt grec': 'Produits Laitiers & Œufs',
  'yaourts': 'Produits Laitiers & Œufs',
  'épinards': 'Fruits & Légumes',
  'épinards frais': 'Fruits & Légumes',
  'éponge': 'Hygiène & Entretien',
  'éponges': 'Hygiène & Entretien',
  'œuf': 'Produits Laitiers & Œufs',
  'œufs': 'Produits Laitiers & Œufs',
};

String getCategoryForProduct(String name) {
  final cleanName = name.trim().toLowerCase();
  if (kProductCategories.containsKey(cleanName)) {
    return kProductCategories[cleanName]!;
  }
  for (final entry in kProductCategories.entries) {
    if (cleanName.contains(entry.key)) {
      return entry.value;
    }
  }
  return 'En vrac';
}

String getProductDefaultUnit(String name) {
  final cleanName = name.trim().toLowerCase();
  if (kProductDefaultUnits.containsKey(cleanName)) {
    return kProductDefaultUnits[cleanName]!;
  }
  for (final entry in kProductDefaultUnits.entries) {
    if (cleanName.contains(entry.key)) {
      return entry.value;
    }
  }
  return 'pc';
}



